name: jailbreak_root_detection
description: Uses RootBeer + DetectFrida for Android root detection and IOSSecuritySuite for iOS jailbreak detection.
version: 1.0.12
homepage: https://github.com/jayghadgeABA/jailbreak_root_detection

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.w3conext.jailbreak_root_detection
        pluginClass: JailbreakRootDetectionPlugin
      ios:
        pluginClass: JailbreakRootDetectionPlugin
